---
# tasks file for wp-install-config

- name: Create directory to download WordPress
  command: mkdir -p /opt/source/wordpress

- name: Download WordPress
  get_url: url=https://www.wordpress.org/latest.tar.gz dest=/opt/source/wordpress/wordpress.tar.gz validate_certs=no

- name: Extract WordPress
  command: "tar xzf /opt/source/wordpress/wordpress.tar.gz -C /var/www/html --strip-components 1"

- name: Send config file
  copy: src=/etc/ansible/roles/wp-install-config/templates/wp-config-sample.php dest=/var/www/html/wp-config.php mode=0644

- name: Final reboot after 20 sec
  reboot:
    reboot_timeout: 20
